name: Testing With Stable Client

on:
  workflow_dispatch:
    inputs:
      syncing_server_js_image_tag:
        type: string
        default: latest
        description: The Docker image tag used for Syncing Server JS container
      api_gateway_image_tag:
        type: string
        default: latest
        description: The Docker image tag used for Api Gateway container
      auth_image_tag:
        type: string
        default: latest
        description: The Docker image tag used for Auth container
      workspace_image_tag:
        type: string
        default: latest
        description: The Docker image tag used for Workspace container
      files_image_tag:
        type: string
        default: latest
        description: The Docker image tag used for Files container

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run E2E Test Suite
        run: yarn test:stable-client
        env:
          SYNCING_SERVER_JS_IMAGE_TAG: ${{ inputs.syncing_server_js_image_tag }}
          API_GATEWAY_IMAGE_TAG: ${{ inputs.api_gateway_image_tag }}
          AUTH_IMAGE_TAG: ${{ inputs.auth_image_tag }}
          WORKSPACE_IMAGE_TAG: ${{ inputs.workspace_image_tag }}
          FILES_IMAGE_TAG: ${{ inputs.files_image_tag }}
